FROM nginx

RUN apt update 
RUN apt install -y gcc libfcgi-dev spawn-fcgi

COPY ./server/mini_server.c /home
RUN gcc /home/mini_server.c -o mini_server -lfcgi

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT spawn-fcgi -p 8080 ./mini_server && nginx -g "daemon off;"
